VIA_ENABLE = yes
# LTO_ENABLE = yes
# CONSOLE_ENABLE = no     # Console for debug(+400)
# AUDIO_ENABLE   = no     # Audio output on port C6
COMMAND_ENABLE		= yes
OLED_ENABLE  = yes
OLED_DRIVER = SSD1306
RGBLIGHT_ENABLE = yes
WS2812_DRIVER = vendor
DEBOUNCE_TYPE = sym_defer_pk